#!/bin/bash
set -euo pipefail
planetfilea=berlin-latest.osm.pbf
#planetfilea=dach-latest.osm.pbf
#planetfilea=germany-latest.osm.pbf
styledir=/home/renderaccount/Myosm2pgsql-themepark
export LUA_PATH="$styledir/lua/?.lua;;"
cd /home/postgres/download
if [ -f $planetfilea ]
then
    rm $planetfilea
fi
# Aufbau der lokalen Postgis-Datenbank mit osm2psql
/usr/bin/wget https://download.geofabrik.de/europe/germany/$planetfilea && /usr/bin/osm2pgsql -O flex --create --slim -C 5000 --style $styledir/config.lua -d themeparktest $planetfilea
# Initialisierung des inkrementellen Datenbankupdates
/usr/bin/osm2pgsql-replication init -d themeparktest --server 'https://planet.openstreetmap.org/replication/minute'
# erstes inkrementelles Datenbankupdate
$styledir/Server_Update/update_osm_planet_dach_mapnik

